name: CI Pipeline

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: npm install

      # Passo 4: Compilar cargo-components
      - name: Build cargo-components
        run: npm run build --workspace=cargo-components

      # Passo 5: Rodar ESLint
      - name: Run ESLint
        run: npm run lint

      # Passo 6: Rodar testes (opcional)
      - name: Run tests
        run: npm test --if-present

      # Passo 7: Gerar builds para todos os microfrontends
      - name: Build all microfrontends
        run: npm run build --workspaces